# database config
spring.datasource.url: jdbc:h2:mem:h2db
spring.h2.console.enabled: true
#spring.jpa.show-sql: true

# app config
app-config:
  simpleKey: "value"
  score_constant:
    low: 50
    medium: 30
    high: 0



